name: Node.js package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        node: [8, 10, 12, 13, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          if [ ${{ matrix.os }} = ubuntu-18.04 ]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt -qq update
            sudo apt install -y g++-4.8
          fi
      - name: Run integration tests
        run: |
          if [ ${{ matrix.os }} = macos-latest -a ${{ matrix.node }} = 6 ]; then
            # Mac bindings will currently not build on Node 6
            exit 0
          fi
          if [ ${{ matrix.os }} = ubuntu-18.04 ]; then
            export CC="g++-4.8"
          fi
          npm install

          if [ ${{ matrix.node }} = 8 ]; then
            # mocha 8+ is not compatible with Node 8
            npm install mocha@7.2.0
          fi

          npm run test
      - name: Lint
        run: |
          if [ ${{ matrix.node }} = 6 ]; then
            # ESLint 6+ is not compatible with Node 6
            exit 0
          elif [ ${{ matrix.node }} = 8 ]; then
            # ESLint 7+ is not compatible with Node 8
            exit 0
          fi
          npm run lint
